root: true
env:
  node: true
  es6: true
extends:
  - 'plugin:@typescript-eslint/recommended'
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
plugins:
  - '@typescript-eslint'
rules:
  no-eval: error
  no-debugger: error
  no-console: error
  no-var: error
  no-unsafe-finally: error
  prefer-const: error
  prefer-rest-params: error
  prefer-spread: error
  no-duplicate-imports: off
